// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/leadhive-ui/Companies.tsx": () => import("../components/mockups/leadhive-ui/Companies.tsx"),
  "./components/mockups/leadhive-ui/Dashboard.tsx": () => import("../components/mockups/leadhive-ui/Dashboard.tsx"),
  "./components/mockups/leadhive-ui/Sidebar.tsx": () => import("../components/mockups/leadhive-ui/Sidebar.tsx")
};
